name: Firebase Deployment with Preview Channels

on:
  push:
    branches:
      - main
      - preview/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd frontend/Event-management
          npm install

      - name: Build
        env:
          CI: false
        run: |
          cd frontend/Event-management
          npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: frontend/Event-management/dist/**

  deploy:
    name: Deploy to Firebase Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: frontend/Event-management/dist

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Preview Channel
        working-directory: frontend/Event-management
        run: firebase hosting:channel:deploy preview-${{ github.ref_name }} --expires 7d
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Production (if on main branch)
        if: github.ref_name == 'main'
        working-directory: frontend/Event-management
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
